name: Build Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --legacy-peer-deps
      - run: npm run build
      - name: Salvar site pronto
        uses: actions/upload-artifact@v4
        with:
          name: Site-Guerreiros-da-Tribo
          path: build
          retention-days: 30
